server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          default-label: master
          uri: file://d:\git\msa\ecommerce\config-file

management:
  endpoints:
    web:
      exposure:
        include: health, refresh, beans, httptrace, busrefresh
