server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native

  cloud:
    config:
      server:
        native:
          search-locations: classpath:native-config
#        git:
#          default-label: master
#          uri: file://d:\git\msa\msa-config-file

management:
  endpoints:
    web:
      exposure:
        include: health, refresh, beans, httptrace, busrefresh
